import Products from "@/features/products/Products";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lazada - Products",
  description: "Generated by create next app",
};

export default async function ProductsPage() {
  return <Products />;
}
