import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lazada - Products",
  description: "Generated by create next app",
};

export default function Products() {
  return <div> Product </div>;
}
