import ProductsContainer from '@/features/products/Products';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Lazada - Products',
  description: 'Generated by create next app'
};

export default ProductsContainer;
