import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";

const roboto = Roboto({
  weight: "400",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Lazada - Mua sắm trực tuyến hàng đầu Việt Nam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, "bg-stone-50")}>{children}</body>
    </html>
  );
}
