import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/core/utils/cn";
import Header from "@/core/components/organisms/Header";
import type { ReactNode } from "react";
import { Toaster } from "sonner";

const roboto = Roboto({
  weight: "400",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Lazada - Mua sắm trực tuyến hàng đầu Việt Nam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  modal: ReactNode;
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, "bg-stone-50")}>
        <Header />
        {modal}
        {children}
        <Toaster richColors position="top-right" closeButton duration={5000} />
      </body>
    </html>
  );
}
