import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Lazada - Not Found',
  description: 'Generated by create next app'
};

export default function NotFound() {
  return <div> Not Found </div>;
}
