import AboutContainer from '@/features/about/About';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Lazada - About',
  description: 'Generated by create next app'
};

export default function AboutPage() {
  return <AboutContainer />;
}
