import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lazada - About",
  description: "Generated by create next app",
};

export default function About() {
  return <div> About </div>;
}
