import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Lazada - About",
  description: "Generated by create next app",
};

export default function AboutPage() {
  redirect("/products");
}
